# Generated by Django 5.2.5 on 2025-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='option_a',
            field=models.CharField(blank=True, default='A', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_b',
            field=models.CharField(blank=True, default='B', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_c',
            field=models.CharField(blank=True, default='C', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_d',
            field=models.CharField(blank=True, default='D', max_length=200),
        ),
    ]
