# Generated by Django 5.2.5 on 2025-08-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mission_option_a_alter_mission_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_option',
            field=models.CharField(max_length=200),
        ),
    ]
