# Generated by Django 5.2.5 on 2025-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mission_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='option_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_d',
            field=models.CharField(max_length=200),
        ),
    ]
