# Generated by Django 5.2.5 on 2025-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mission_option_a_alter_mission_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_option',
            field=models.CharField(blank=True, default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_a',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_b',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
